apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecret
  namespace: sealedsecret
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sealedsecret
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: sealedsecret
    repoURL: hhttps://github.com/bitnami-labs/sealed-secrets
    targetRevision: HEAD