apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-basic
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: ingress-basic
    repoURL: https://helm.nginx.com/stable
    targetRevision: HEAD


