apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecret
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: sealedsecret
    repoURL: hhttps://github.com/bitnami-labs/sealed-secrets
    targetRevision: HEAD


    argocd login https://20.212.131.76/ --username admin --password $(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo) --insecure