apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-sealedsecret
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: v1.16.1
    helm:
      releaseName: sealed-secrets
      values: |
        commandArgs:
          - '--update-status'
  destination:
    server: {{ .Values.destination.server }}
    namespace: kube-system