apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ingress
  namespace: argocd
spec:
  destination:
    namespace: ingress-basic
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: ingress-nginx
    path: ingress-basic
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 3.35.0
