apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-basic
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: ingress-nginx
    helm:
      # parameters: []
      values: |
        controller:
          ingressClass: wso2
          replicaCount: 3
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.0.19
    targetRevision: HEAD
