apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wso2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: wso2
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: wso2
    repoURL: https://github.com/wso2/kubernetes-apim
    targetRevision: HEAD

