apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.destination.env }}-{{ .Values.ingressNginx.name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-basic
    server: {{ .Values.destination.server }}
  project: default
  source:
    chart: ingress-nginx
    helm:
      # parameters: []
      values: |
        controller:
          replicaCount: 3
    repoURL: https://github.com/kubernetes/ingress-nginx/charts/ingress-nginx
    targetRevision: HEAD
