apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-basic
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/ingress-nginx
    repoURL:  https://github.com/kubernetes/ingress-nginx
    targetRevision: HEAD